<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('goals', function(Blueprint $t){ $t->id(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->string('title'); $t->string('category')->default('Academics'); $t->string('target')->nullable(); $t->string('success_criteria')->nullable(); $t->unsignedTinyInteger('progress')->default(0); $t->string('status')->default('active'); $t->timestamps(); });
Schema::create('rewards', function(Blueprint $t){ $t->id(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->string('name'); $t->string('condition')->nullable(); $t->string('category')->default('Food'); $t->unsignedTinyInteger('progress')->default(0); $t->string('status')->default('locked'); $t->timestamp('earned_at')->nullable(); $t->timestamps(); });
Schema::create('teacher_feedback', function(Blueprint $t){ $t->id(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->string('teacher_name'); $t->string('teacher_email')->nullable(); $t->string('subject')->nullable(); $t->string('engagement')->nullable(); $t->string('work_completion')->nullable(); $t->text('comment')->nullable(); $t->timestamps(); });
Schema::create('teacher_links', function(Blueprint $t){ $t->id(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->string('token')->unique(); $t->boolean('active')->default(true); $t->timestamp('expires_at')->nullable(); $t->timestamps(); });
Schema::create('teacher_requests', function(Blueprint $t){ $t->id(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->foreignId('parent_id')->constrained('users')->cascadeOnDelete(); $t->string('teacher_name')->nullable(); $t->string('teacher_email')->nullable(); $t->text('message')->nullable(); $t->string('urgency')->default('normal'); $t->string('status')->default('sent'); $t->timestamps(); });
Schema::create('alerts', function(Blueprint $t){ $t->id(); $t->foreignId('student_id')->constrained()->cascadeOnDelete(); $t->string('type')->default('academics'); $t->string('title'); $t->text('description')->nullable(); $t->string('priority')->default('medium'); $t->string('status')->default('active'); $t->timestamp('resolved_at')->nullable(); $t->timestamps(); });
} public function down(): void { foreach(['alerts','teacher_requests','teacher_links','teacher_feedback','rewards','goals'] as $table) Schema::dropIfExists($table); } };
